default:
  http_metas:
    content-type: text/html

  metas:
    title:        ODIN CAPITAL
    robots:       index, follow
    description:  ODIN CAPITAL
    keywords:     ODIN CAPITAL
    language:     en

  stylesheets:    []

  javascripts:    []

  has_layout:     on
  layout:         layout
